spring.application.name=aws
# DB config
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

# Hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

# Logging and SQL display
logging.level.org.hibernate=ERROR
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
# S3 config
aws.access.key.id=
aws.secret.access.key=
aws.region=
aws.s3.bucket.name=

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB